Repository IoTresor/geo-api, pull requests merged in 2020-06, with the labels that each got.

#41 Set up `pino` Logging Framework
  api/.env
  api/build/src/Geolocation.js
  api/build/src/Particle.js
  api/build/src/index.js
  api/package-lock.json
  api/package.json
  api/src/Geolocation.ts
  api/src/Particle.ts
  api/src/index.ts
Labels: refactor, server

#45 #25 Particle Devices + IP
  api/build/Geolocation.js
  api/build/Particle.js
  api/build/index.js
  api/build/src/Particle.js
  api/build/src/index.js
  api/package-lock.json
  api/package.json
  api/src/Particle.ts
  api/src/index.ts
  package-lock.json
Labels: discussion, enhancement

#47 #NA Update latest working version of QA from Dev
  Geolocation.js
  api/.env
  api/build/Geolocation.js
  api/build/Particle.js
  api/build/index.js
  api/build/src/Geolocation.js
  api/build/src/Particle.js
  api/build/src/index.js
  api/package-lock.json
  api/package.json
  api/src/Geolocation.ts
  api/src/Particle.ts
  api/src/index.ts
  device/grabIP.cc
  package-lock.json
Labels: discussion

#54 Programmatically Pulls IP and Set Up Recurring API Calls
  .gitignore
  .travis.yml
  api/build/src/Geolocation.js
  api/build/src/Particle.js
  api/build/src/index.js
  api/build/test/test.js
  api/package-lock.json
  api/package.json
  api/src/Geolocation.ts
  api/src/Particle.ts
  api/src/index.ts
  api/test/test.ts
  web/.env
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/GeoLocationMap.tsx
  web/src/Home.tsx
  web/tests/tests.spec.js
Labels: client, server

#51 [Automerge] Qa
  README.md
  mobile/.kodiak.toml
Labels: automerge
